baseURL: "https://vast-site.danguns.ca"
title: "VAST"
languageCode: "en-us"

# Language settings
contentDir: "content/en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

# Markup settings for Docsy
markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    style: "github"

# Module configuration
module:
  imports:
  - path: github.com/google/docsy
    disable: false
  - path: github.com/google/docsy/dependencies
    disable: false

# Site parameters
params:
  github_repo: "https://github.com/dgunzy/VAST"
  github_branch: "main"
  
  # Copyright
  copyright:
    authors: "VAST Foundation"
    from_year: 2024
  
  # Privacy policy
  privacy_policy: "/privacy"
  
  # User interface configuration
  ui:
    showLightDarkModeMenu: true
    sidebar_menu_compact: true
    breadcrumb_disable: false
    navbar_logo: true
    footer_about_enable: true
    
  # Color theme
  prism_syntax_highlighting: false

      
# Taxonomies
taxonomies:
  tag: tags
  category: categories
  