baseURL: "https://vast-site.danguns.ca"
title: "VAST"
languageCode: "en-us"

module:
  imports:
    - path: github.com/theNewDynamic/gohugo-theme-ananke/v2

# Content and language settings
contentDir: "content"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

# Markup settings
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github"

# Menu configuration
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3
    - name: "Contact"
      url: "/contact/"
      weight: 4

# Ananke theme parameters
params:
  # Basic site info
  description: "VAST brings the benefits of simulation training to a wide range of contexts through portable, locally adaptable and affordable courses."
  
  # Logo and branding
  site_logo: "images/logo.svg"
  
  # Colors and styling
  background_color_class: "bg-near-white"
  body_classes: "avenir bg-near-white"
  text_color: "dark-gray"
  
  # Featured image settings
  featured_image: "/images/simulation.jpg"  # Add your hero image here
  featured_image_class: "cover bg-center"
  cover_dimming_class: "bg-black-40"
  
  # Contact information
  email: "info@vast.org"
  
  # Social media (add your social links)
  # github: "https://github.com/yourusername"
  # twitter: "https://twitter.com/yourusername"
  # linkedin: "https://linkedin.com/company/vast"
  
  # Copyright
  copyright: "Copyright © 2025 VAST Foundation. All Rights Reserved."
  
  # Date format
  date_format: "January 2, 2006"
  
  # Show reading time and word count
  show_reading_time: true
  
  # Main sections (for blog functionality)
  mainSections: ["blog"]
  
  # Homepage content
  recent_posts:
    enable: true
    title: "Latest Updates"
  
  # Contact form (using Formspree)
  # Uncomment and add your Formspree endpoint when ready
  # formspree_action: "https://formspree.io/f/your-form-id"

# Taxonomies
taxonomies:
  tag: tags
  category: categories
  author: authors

# Privacy settings (optional)
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: false
    anonymizeIP: true
  instagram:
    disable: true
  twitter:
    disable: false
  vimeo:
    disable: true
  youtube:
    disable: false