baseURL: "https://vast-site.danguns.ca"
title: "VAST"
languageCode: "en-us"
theme: "universal"

# Content and language settings
contentDir: "content"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

# Markup settings
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github"

# Menu configuration
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3
    - name: "Contact"
      url: "/contact/"
      weight: 4

# Site parameters for Universal theme
params:
  style: "blue"  # Color scheme: default, blue, green, marsala, pink, red, turquoise, violet
  
  # Logo settings
  logo: "img/logo.svg"
  logo_small: "img/logo-small.svg"
  disabled_logo: false
  logo_text: "VAST"
  
  # Contact information
  email: "info@vast.org"
  
  # Copyright
  copyright: "Copyright &copy; 2025 VAST Foundation. All Rights Reserved."
  
  # Date format
  date_format: "January 2, 2006"
  
  # Main sections (for blog functionality)
  mainSections: ["blog"]
  
  # Homepage sections
  about_us: "<p>VAST brings the benefits of simulation training to a wide range of contexts. The Course is designed to be portable, locally adaptable and affordable.</p>"
  
  # Contact form (using Formspree - you'll need to set this up)
  # formspree_action: "https://formspree.io/f/your-form-id"
  contact_form_ajax: false
  
  # Footer settings
  footer:
    recent_posts:
      enable: true
  
  # Recent posts settings
  recent_posts:
    enable: true
    title: "Latest Updates"
    subtitle: "Stay informed about our latest training programs and developments"
    hide_summary: false
  
  # Features section
  features:
    enable: true
    cols: 3
  
  # Testimonials (displaying team members)
  testimonials:
    enable: true
    title: "VAST Ltd Board"
    subtitle: "Meet the dedicated professionals leading our mission to improve anesthesia safety worldwide"
  
  # Clients/Partners section
  clients:
    enable: true
    title: "Our Partners"
    subtitle: "We work with leading healthcare organizations worldwide"
  
  # Carousel settings
  CarouselHomepage:
    enable: true
    auto_play: true
    slide_speed: 2000
    pagination_speed: 1000
  
  # Carousel settings for testimonials
  CarouselTestimonials:
    items: 3
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000
  
  # Carousel settings for clients
  CarouselCustomers:
    items: 6
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000

# Taxonomies
taxonomies:
  tag: tags
  category: categories
  author: authors